---

- name: Download and install elasticsearch gpg public signing key
  apt_key:
    url:   "{{ elasticsearch_signing_key_url }}"
    state: present

- name: Add elasticsearch apt repository definition to apt sources list | v2.x or earlier
  apt_repository:
    repo:         "{{ elasticsearch_2_apt_repo }}"
    update_cache: yes
    state:        present
  when: elasticsearch_version_major|int < 5

- name: Add elasticsearch apt repository definition to apt sources list | v5.x or later
  apt_repository:
    repo:         "{{ elasticsearch_apt_repo }}"
    update_cache: yes
    state:        present
  when: elasticsearch_version_major|int >= 5

- name: Install elasticsearch
  apt: 
    name:  "elasticsearch={{ elasticsearch_version|default('*') }}"
    state: present
