---

- name: Elasticsearch Install
  include: "install-{{ ansible_os_family|lower }}.yml"

#- name: Set mmap count kernel parameter for elasticsearch
#  template:
#    src:  sysctl.elasticsearch.conf.j2
#    dest: /etc/sysctl.d/60-elasticsearch.conf
#    mode: 0644
#  register: mmap
#
#- name: Load in mmap count kernel parameter for elasticsearch
#  shell: >
#      sysctl -p /etc/sysctl.d/60-elasticsearch.conf
#  when: mmap|changed

- name: Set elasticsearch plugin cmd
  set_fact:
    elasticsearch_plugin_cmd: "{{ elasticsearch_home_dir }}/bin/plugin"
    _list_plugins_cmd: "| grep -v 'Installed plugins' | awk '{print $2}'"
  when: elasticsearch_version_major == 2

- name: Get list of installed elasticsearch plugins
  shell: >
    {{ elasticsearch_plugin_cmd }} list {{ _list_plugins_cmd_filter|default('') }}
  register: plugins

- debug: msg="Installed plugins - {{ plugins.stdout_lines|join(', ') }}"

- name: Install elasticsearch plugin
  shell: >
    {{ elasticsearch_plugin_cmd }} install -b {{ item }}
  when: item not in plugins.stdout_lines
  with_items: "{{ elasticsearch_plugins }}"

- name: Ensure elasticsearch home dir is created
  file: 
    path:  "{{ elasticsearch_home_dir }}" 
    owner: "root"
    group: "root"
    mode:  0755
    state: directory

- name: Ensure elasticsearch data dir is created
  file: 
    path:  "{{ elasticsearch_data_dir }}" 
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode:  0755
    state: directory

- name: Ensure elasticsearch conf dir is created
  file: 
    path:  "{{ elasticsearch_conf_dir }}" 
    owner: "root"
    group: "{{ elasticsearch_group }}"
    mode:  0755
    state: directory

- name: Create elasticsearch config
  template: 
    src:   elasticsearch.yml.j2
    dest:  "{{ elasticsearch_conf_dir }}/elasticsearch.yml"
    owner: "root"
    group: "{{ elasticsearch_group }}"
    mode:  0644
  notify: 
    - Restart elasticsearch

## new in 5.x
- name: Create elasticsearch jvm options config
  template: 
    src:   jvm.options.j2
    dest:  "{{ elasticsearch_conf_dir }}/jvm.options"
    owner: "root"
    group: "{{ elasticsearch_group }}"
    mode:  0644
  when: elasticsearch_version_major >= 5
  notify: 
    - Restart elasticsearch

#- pause: minutes=10

- name: Create elasticsearch logging config
  copy: 
    src:   logging.yml
    dest:  "{{ elasticsearch_conf_dir }}/logging.yml"
    owner: "root"
    group: "{{ elasticsearch_group }}"
    mode:  0644
  when: elasticsearch_version_major < 5
  notify: 
    - Restart elasticsearch

- name: Create elasticsearch scripts dir
  file: 
    path:  "{{ elasticsearch_scripts_dir }}"
    owner: "root"
    group: "{{ elasticsearch_group }}"
    mode:  0755
    state: directory
  notify: 
    - Restart elasticsearch

- name: Create elasticsearch log dir
  file: 
    path:  "{{ elasticsearch_log_dir }}"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode:  0755
    state: directory
  notify: 
    - Restart elasticsearch

- name: Create elasticsearch default settings file
  template: 
    src:   etc.default.elasticsearch.j2
    dest:  "/etc/default/elasticsearch"
    owner: root
    group: root
    mode:  0644
  notify: 
    - Restart elasticsearch

- name: Start elasticsearch
  service: name=elasticsearch enabled=yes state=started

- name: Wait for elasticsearch to start
  wait_for: 
    host: "{{ elasticsearch_network_host }}"
    port: "{{ elasticsearch_http_port }}"
